from __future__ import annotations

import shutil
from collections.abc import Mapping
from pathlib import Path

from muse.agent_instructions import render_agent_instructions
from muse.live_preflight import check_live_openai_environment
from muse.mcp_config import HostConfigFormat, render_mcp_config
from muse.models import FrozenModel

MARKER_FILE = ".muse-external-dogfood"


class ExternalDogfoodReport(FrozenModel):
    workspace: str
    host: str
    instruction_target: str
    created_files: tuple[str, ...]
    host_config_path: str
    instructions_path: str
    doctor_status: str
    pricing_source: str | None
    mcp_smoke_status: str
    ready_for_manual_agent_test: bool
    next_steps: tuple[str, ...]


def run_external_dogfood(
    *,
    workspace: Path,
    host: str = "generic-json",
    instruction_target: str = "agents-md",
    include_env: bool = False,
    force: bool = False,
    environ: Mapping[str, str] | None = None,
) -> ExternalDogfoodReport:
    repo_path = workspace.expanduser().resolve()
    _prepare_workspace(repo_path, force=force)

    created_files: list[str] = []
    _write_text(
        repo_path / MARKER_FILE,
        "Generated by muse-external-dogfood.\n",
        created_files,
        repo_path=repo_path,
    )
    _write_sample_repo(repo_path, created_files)

    snippet = render_mcp_config(host=host, include_env=include_env)
    host_config_path = _host_config_path(repo_path, host=snippet.host, format=snippet.format)
    _write_text(host_config_path, snippet.content, created_files, repo_path=repo_path)

    instructions = render_agent_instructions(target=instruction_target)
    instructions_path = _instruction_path(repo_path, instructions.recommended_file)
    _write_text(instructions_path, instructions.content, created_files, repo_path=repo_path)

    preflight = check_live_openai_environment(environ)
    ready = preflight.ok

    return ExternalDogfoodReport(
        workspace=str(repo_path),
        host=snippet.host,
        instruction_target=instructions.target,
        created_files=tuple(sorted(created_files)),
        host_config_path=str(host_config_path),
        instructions_path=str(instructions_path),
        doctor_status=preflight.status.value,
        pricing_source=preflight.pricing_source,
        mcp_smoke_status="skipped",
        ready_for_manual_agent_test=ready,
        next_steps=_next_steps(
            repo_path=repo_path,
            ready_for_manual_agent_test=ready,
            host_config_path=host_config_path,
            instructions_path=instructions_path,
        ),
    )


def _prepare_workspace(repo_path: Path, *, force: bool) -> None:
    marker_path = repo_path / MARKER_FILE
    if not repo_path.exists():
        repo_path.mkdir(parents=True)
        return
    if not repo_path.is_dir():
        raise ValueError(f"workspace must be a directory: {repo_path}")
    if not marker_path.exists():
        raise ValueError(
            f"refusing to replace unmarked workspace: {repo_path}. "
            f"Create an empty path or use a directory containing {MARKER_FILE}."
        )
    if force:
        shutil.rmtree(repo_path)
        repo_path.mkdir(parents=True)


def _write_sample_repo(repo_path: Path, created_files: list[str]) -> None:
    _write_text(
        repo_path / "pyproject.toml",
        "\n".join(
            [
                "[project]",
                'name = "muse-external-dogfood-sample"',
                'version = "0.0.0"',
                'requires-python = ">=3.12"',
                "",
                "[tool.pytest.ini_options]",
                'testpaths = ["tests"]',
                "",
            ]
        ),
        created_files,
        repo_path=repo_path,
    )
    _write_text(
        repo_path / "src" / "retry_policy.py",
        "\n".join(
            [
                "from __future__ import annotations",
                "",
                "",
                "def next_retry_delay(attempt: int) -> int:",
                "    if attempt < 1:",
                '        raise ValueError("attempt must be positive")',
                "    return min(2 ** (attempt - 1), 30)",
                "",
            ]
        ),
        created_files,
        repo_path=repo_path,
    )
    _write_text(
        repo_path / "tests" / "test_retry_policy.py",
        "\n".join(
            [
                "from __future__ import annotations",
                "",
                "from src.retry_policy import next_retry_delay",
                "",
                "",
                "def test_retry_delay_increases_until_cap() -> None:",
                "    assert [next_retry_delay(i) for i in range(1, 7)] == [1, 2, 4, 8, 16, 30]",
                "",
            ]
        ),
        created_files,
        repo_path=repo_path,
    )


def _host_config_path(repo_path: Path, *, host: str, format: HostConfigFormat) -> Path:
    if host == "codex":
        return repo_path / ".codex" / "config.toml"
    if format is HostConfigFormat.JSON:
        return repo_path / ".mcp.json"
    return repo_path / "muse-mcp-config.toml"


def _instruction_path(repo_path: Path, recommended_file: str) -> Path:
    if recommended_file in {"project instructions", "Claude project instructions"}:
        return repo_path / "MUSE_INSTRUCTIONS.md"
    return repo_path / recommended_file


def _write_text(
    path: Path,
    content: str,
    created_files: list[str],
    *,
    repo_path: Path,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    created_files.append(path.relative_to(repo_path).as_posix())


def _next_steps(
    *,
    repo_path: Path,
    ready_for_manual_agent_test: bool,
    host_config_path: Path,
    instructions_path: Path,
) -> tuple[str, ...]:
    steps = [
        f"cd {repo_path}",
        f"Review MCP config at {host_config_path}",
        f"Review agent instructions at {instructions_path}",
        "Run muse-mcp-doctor --json",
    ]
    if ready_for_manual_agent_test:
        steps.append('Ask your agent to call muse_plan for: "Design a retry strategy"')
    else:
        steps.append("Set OPENAI_API_KEY, OPENAI_ECONOMY_MODEL, and OPENAI_STRONG_MODEL.")
    return tuple(steps)
